/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Docusaurus",
  "tagline": "Build optimized websites quickly, focus on your content",
  "organizationName": "facebook",
  "projectName": "docusaurus",
  "baseUrl": "/",
  "baseUrlIssueBanner": true,
  "url": "https://docusaurus.io",
  "future": {
    "experimental_storage": {
      "namespace": true,
      "type": "localStorage"
    },
    "experimental_router": "browser"
  },
  "trailingSlash": false,
  "stylesheets": [
    {
      "href": "/katex/katex.min.css",
      "type": "text/css"
    }
  ],
  "i18n": {
    "defaultLocale": "en",
    "localeConfigs": {
      "en": {
        "direction": "rtl"
      }
    },
    "locales": [
      "en",
      "fr",
      "pt-BR",
      "ko",
      "zh-CN"
    ],
    "path": "i18n"
  },
  "webpack": {},
  "markdown": {
    "format": "detect",
    "mermaid": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "remarkRehypeOptions": {
      "footnoteLabel": "Footnotes"
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "onBrokenLinks": "warn",
  "onBrokenAnchors": "warn",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/docusaurus.ico",
  "customFields": {
    "crashTest": false,
    "isDeployPreview": false,
    "description": "An optimized site generator in React. Docusaurus helps you to move fast and write content. Build documentation websites, blogs, marketing pages, and more.",
    "announcedVersion": "3.3"
  },
  "staticDirectories": [
    "static",
    "C:\\Users\\vadim\\Downloads\\MD\\docusaurus\\website\\_dogfooding\\_asset-tests",
    "C:\\Users\\vadim\\Downloads\\MD\\docusaurus\\website\\_dogfooding\\non-existent"
  ],
  "themes": [
    "live-codeblock",
    null
  ],
  "plugins": [
    [
      "./src/plugins/changelog/index.js",
      {
        "blogTitle": "Docusaurus changelog",
        "blogDescription": "Keep yourself up-to-date about new features in every release",
        "blogSidebarCount": "ALL",
        "blogSidebarTitle": "Changelog",
        "routeBasePath": "/changelog",
        "showReadingTime": false,
        "postsPerPage": 20,
        "archiveBasePath": null,
        "authorsMapPath": "authors.json",
        "feedOptions": {
          "type": "all",
          "title": "Docusaurus changelog",
          "description": "Keep yourself up-to-date about new features in every release",
          "copyright": "Copyright © 2024 Facebook, Inc.",
          "language": "en"
        }
      }
    ],
    [
      "content-docs",
      {
        "id": "community",
        "path": "community",
        "routeBasePath": "community",
        "remarkPlugins": [
          null
        ],
        "editCurrentVersion": true,
        "sidebarPath": "./sidebarsCommunity.js",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true
      }
    ],
    [
      "client-redirects",
      {
        "fromExtensions": [
          "html"
        ],
        "redirects": [
          {
            "from": [
              "/docs/support",
              "/docs/next/support"
            ],
            "to": "/community/support"
          },
          {
            "from": [
              "/docs/team",
              "/docs/next/team"
            ],
            "to": "/community/team"
          },
          {
            "from": [
              "/docs/resources",
              "/docs/next/resources"
            ],
            "to": "/community/resources"
          },
          {
            "from": [
              "/home/"
            ],
            "to": "/"
          },
          {
            "from": [
              "/home/qs"
            ],
            "to": "/?a=1"
          },
          {
            "from": [
              "/home/anchor"
            ],
            "to": "/#anchor"
          },
          {
            "from": [
              "/home/absolute"
            ],
            "to": "https://docusaurus.io/"
          },
          {
            "from": [
              "/home/absolute/qs"
            ],
            "to": "https://docusaurus.io/?a=1"
          },
          {
            "from": [
              "/home/absolute/anchor"
            ],
            "to": "https://docusaurus.io/#anchor"
          }
        ]
      }
    ],
    [
      "ideal-image",
      {
        "quality": 70,
        "max": 1030,
        "min": 640,
        "steps": 2,
        "disableInDev": true
      }
    ],
    [
      "pwa",
      {
        "offlineModeActivationStrategies": [
          "appInstalled",
          "standalone",
          "queryString"
        ],
        "swCustom": "C:\\Users\\vadim\\Downloads\\MD\\docusaurus\\website\\src\\sw.js",
        "pwaHead": [
          {
            "tagName": "link",
            "rel": "icon",
            "href": "img/docusaurus.png"
          },
          {
            "tagName": "link",
            "rel": "manifest",
            "href": "manifest.json"
          },
          {
            "tagName": "meta",
            "name": "theme-color",
            "content": "rgb(37, 194, 160)"
          },
          {
            "tagName": "meta",
            "name": "apple-mobile-web-app-capable",
            "content": "yes"
          },
          {
            "tagName": "meta",
            "name": "apple-mobile-web-app-status-bar-style",
            "content": "#000"
          },
          {
            "tagName": "link",
            "rel": "apple-touch-icon",
            "href": "img/docusaurus.png"
          },
          {
            "tagName": "link",
            "rel": "mask-icon",
            "href": "img/docusaurus.png",
            "color": "rgb(62, 204, 94)"
          },
          {
            "tagName": "meta",
            "name": "msapplication-TileImage",
            "content": "img/docusaurus.png"
          },
          {
            "tagName": "meta",
            "name": "msapplication-TileColor",
            "content": "#000"
          }
        ]
      }
    ],
    "@docusaurus/theme-mermaid",
    "./src/plugins/featureRequests/FeatureRequestsPlugin.js",
    [
      "content-docs",
      {
        "id": "docs-tests",
        "routeBasePath": "/tests/docs",
        "sidebarPath": "_dogfooding/docs-tests-sidebars.js",
        "versions": {
          "current": {
            "noIndex": true
          }
        },
        "path": "_dogfooding/_docs tests",
        "showLastUpdateTime": true,
        "showLastUpdateAuthor": true
      }
    ],
    [
      "@docusaurus/plugin-content-blog",
      {
        "id": "blog-tests",
        "path": "_dogfooding/_blog tests",
        "routeBasePath": "/tests/blog",
        "editUrl": "https://github.com/facebook/docusaurus/edit/main/website/_dogfooding/_blog-tests",
        "postsPerPage": 3,
        "feedOptions": {
          "type": "all",
          "title": "Docusaurus Tests Blog",
          "copyright": "Copyright © 2024 Facebook, Inc."
        }
      }
    ],
    [
      "C:\\Users\\vadim\\Downloads\\MD\\docusaurus\\packages\\docusaurus-plugin-content-pages\\lib\\index.js",
      {
        "id": "pages-tests",
        "path": "_dogfooding/_pages tests",
        "routeBasePath": "/tests/pages",
        "showLastUpdateTime": true,
        "showLastUpdateAuthor": true
      }
    ],
    null
  ],
  "presets": [
    [
      "classic",
      {
        "debug": true,
        "docs": {
          "path": "docs",
          "sidebarPath": "sidebars.ts",
          "admonitions": {
            "keywords": [
              "my-custom-admonition"
            ]
          },
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "remarkPlugins": [
            [
              null,
              {
                "sync": true
              }
            ],
            null,
            null
          ],
          "rehypePlugins": [
            null
          ],
          "disableVersioning": false,
          "lastVersion": "current",
          "onlyIncludeVersions": [
            "current",
            "3.3.2",
            "3.2.1"
          ],
          "versions": {
            "current": {
              "label": "Canary 🚧"
            }
          }
        },
        "blog": {
          "path": "blog",
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "remarkPlugins": [
            null
          ],
          "postsPerPage": 5,
          "feedOptions": {
            "type": "all",
            "copyright": "Copyright © 2024 Facebook, Inc."
          },
          "blogTitle": "Docusaurus blog",
          "blogDescription": "Read blog posts about Docusaurus from the team",
          "blogSidebarCount": "ALL",
          "blogSidebarTitle": "All our posts"
        },
        "pages": {
          "remarkPlugins": [
            null
          ],
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true
        },
        "theme": {
          "customCss": [
            "./src/css/custom.css",
            "./_dogfooding/dogfooding.css"
          ]
        },
        "gtag": {
          "trackingID": [
            "G-E5CR2Q1NRE"
          ]
        },
        "sitemap": {
          "ignorePatterns": [
            "/tests/{blog,pages}/**"
          ],
          "lastmod": "date",
          "priority": null,
          "changefreq": null
        }
      }
    ]
  ],
  "themeConfig": {
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "announcementBar": {
      "id": "announcementBar-v3.3",
      "content": "🎉️ <b><a target=\"_blank\" href=\"https://docusaurus.io/blog/releases/3.3\">Docusaurus v3.3</a> is out!</b> 🥳️",
      "isCloseable": true
    },
    "prism": {
      "additionalLanguages": [
        "java",
        "latex",
        "haskell",
        "matlab",
        "php",
        "powershell",
        "bash",
        "diff",
        "json",
        "scss"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-error-line",
          "line": "This will error"
        }
      ],
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          },
          {
            "types": [
              "title"
            ],
            "style": {
              "color": "#0550AE",
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "parameter"
            ],
            "style": {
              "color": "#953800"
            }
          },
          {
            "types": [
              "boolean",
              "rule",
              "color",
              "number",
              "constant",
              "property"
            ],
            "style": {
              "color": "#005CC5"
            }
          },
          {
            "types": [
              "atrule",
              "tag"
            ],
            "style": {
              "color": "#22863A"
            }
          },
          {
            "types": [
              "script"
            ],
            "style": {
              "color": "#24292E"
            }
          },
          {
            "types": [
              "operator",
              "unit",
              "rule"
            ],
            "style": {
              "color": "#D73A49"
            }
          },
          {
            "types": [
              "font-matter",
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#C6105F"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "#116329"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "#0550AE"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "color": "#CF222E"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "#8250DF"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "#6F42C1"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "#E36209"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "#6B6B6B"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#D4D4D4",
          "backgroundColor": "#212121"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          },
          {
            "types": [
              "title"
            ],
            "style": {
              "color": "#569CD6",
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "property",
              "parameter"
            ],
            "style": {
              "color": "#9CDCFE"
            }
          },
          {
            "types": [
              "script"
            ],
            "style": {
              "color": "#D4D4D4"
            }
          },
          {
            "types": [
              "boolean",
              "arrow",
              "atrule",
              "tag"
            ],
            "style": {
              "color": "#569CD6"
            }
          },
          {
            "types": [
              "number",
              "color",
              "unit"
            ],
            "style": {
              "color": "#B5CEA8"
            }
          },
          {
            "types": [
              "font-matter"
            ],
            "style": {
              "color": "#CE9178"
            }
          },
          {
            "types": [
              "keyword",
              "rule"
            ],
            "style": {
              "color": "#C586C0"
            }
          },
          {
            "types": [
              "regex"
            ],
            "style": {
              "color": "#D16969"
            }
          },
          {
            "types": [
              "maybe-class-name"
            ],
            "style": {
              "color": "#4EC9B0"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "#4FC1FF"
            }
          }
        ]
      }
    },
    "image": "img/docusaurus-social-card.jpg",
    "algolia": {
      "appId": "X1Z85QJPUV",
      "apiKey": "bf7211c161e8205da2f933a02534105a",
      "indexName": "docusaurus-2",
      "replaceSearchResultPathname": {
        "from": "\\^\\\\/docs\\\\/next",
        "to": "/docs"
      },
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "navbar": {
      "hideOnScroll": true,
      "title": "Docusaurus",
      "logo": {
        "alt": "",
        "src": "img/docusaurus.svg",
        "srcDark": "img/docusaurus_keytar.svg",
        "width": 32,
        "height": 32
      },
      "items": [
        {
          "type": "doc",
          "position": "left",
          "docId": "introduction",
          "label": "Docs"
        },
        {
          "type": "docSidebar",
          "position": "left",
          "sidebarId": "api",
          "label": "API"
        },
        {
          "to": "blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "to": "showcase",
          "label": "Showcase",
          "position": "left"
        },
        {
          "to": "/community/support",
          "label": "Community",
          "position": "left",
          "activeBaseRegex": "/community/"
        },
        {
          "type": "doc",
          "docId": "index",
          "label": "Tests",
          "docsPluginId": "docs-tests",
          "position": "left"
        },
        {
          "to": "/__docusaurus/debug",
          "label": "Debug",
          "position": "left"
        },
        {
          "type": "custom-dogfood-navbar-item",
          "content": "😉",
          "position": "left"
        },
        {
          "type": "docsVersionDropdown",
          "position": "right",
          "dropdownActiveClassDisabled": true,
          "dropdownItemsAfter": [
            {
              "type": "html",
              "value": "<hr class=\"dropdown-separator\">"
            },
            {
              "type": "html",
              "className": "dropdown-archived-versions",
              "value": "<b>Archived versions</b>"
            },
            {
              "label": "2.3.1",
              "href": "https://docusaurus-archive-october-2023.netlify.app/docs/2.3.1"
            },
            {
              "label": "2.2.0",
              "href": "https://docusaurus-archive-october-2023.netlify.app/docs/2.2.0"
            },
            {
              "label": "2.1.0",
              "href": "https://docusaurus-archive-october-2023.netlify.app/docs/2.1.0"
            },
            {
              "label": "2.0.1",
              "href": "https://docusaurus-archive-october-2023.netlify.app/docs/2.0.1"
            },
            {
              "href": "https://v1.docusaurus.io",
              "label": "1.x.x"
            },
            {
              "type": "html",
              "value": "<hr class=\"dropdown-separator\">"
            },
            {
              "to": "/versions",
              "label": "All versions"
            }
          ],
          "dropdownItemsBefore": []
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsAfter": [
            {
              "type": "html",
              "value": "<hr style=\"margin: 0.3rem 0;\">"
            },
            {
              "href": "https://github.com/facebook/docusaurus/issues/3526",
              "label": "Help Us Translate"
            }
          ],
          "dropdownItemsBefore": []
        },
        {
          "href": "https://github.com/facebook/docusaurus",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Learn",
          "items": [
            {
              "label": "Introduction",
              "to": "docs"
            },
            {
              "label": "Installation",
              "to": "docs/installation"
            },
            {
              "label": "Migration from v1 to v2",
              "to": "docs/migration"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Stack Overflow",
              "href": "https://stackoverflow.com/questions/tagged/docusaurus"
            },
            {
              "label": "Feature Requests",
              "to": "/feature-requests"
            },
            {
              "label": "Discord",
              "href": "https://discordapp.com/invite/docusaurus"
            },
            {
              "label": "Help",
              "to": "/community/support"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "to": "blog"
            },
            {
              "label": "Changelog",
              "to": "/changelog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/facebook/docusaurus"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/docusaurus"
            },
            {
              "html": "\n                <a href=\"https://www.netlify.com\" target=\"_blank\" rel=\"noreferrer noopener\" aria-label=\"Deploys by Netlify\">\n                  <img src=\"https://www.netlify.com/img/global/badges/netlify-color-accent.svg\" alt=\"Deploys by Netlify\" width=\"114\" height=\"51\" />\n                </a>\n              "
            },
            {
              "html": "\n                <a href=\"https://argos-ci.com\" target=\"_blank\" rel=\"noreferrer noopener\" aria-label=\"Covered by Argos\">\n                  <img src=\"https://argos-ci.com/badge.svg\" alt=\"Covered by Argos\" width=\"133\" height=\"20\" />\n                </a>\n              "
            }
          ]
        },
        {
          "title": "Legal",
          "items": [
            {
              "label": "Privacy",
              "href": "https://opensource.facebook.com/legal/privacy/"
            },
            {
              "label": "Terms",
              "href": "https://opensource.facebook.com/legal/terms/"
            },
            {
              "label": "Cookie Policy",
              "href": "https://opensource.facebook.com/legal/cookie-policy/"
            }
          ]
        }
      ],
      "logo": {
        "alt": "Meta Open Source Logo",
        "src": "/img/meta_opensource_logo_negative.svg",
        "href": "https://opensource.fb.com"
      },
      "copyright": "Copyright © 2024 Meta Platforms, Inc. Built with Docusaurus."
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "onDuplicateRoutes": "warn",
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
